### ISSUE TITLE
MenuItem Fields: FM field styling blocks editing the menu item's label

### ISSUE THREAD

**Issue by goodguyry** [alleyinteractive/wordpress-fieldmanager#856]
**Version**: 1.5.0

After adding FM fields to menu items, I found that the field group's CSS positions it in a manner that prevents editing the menu item label.

My temporary fix is to add the following CSS to unset `.fm-field`'s `position: relative`, which fixes the issue, even if it's not the root cause.

```scss
.fm-wrapper[class*='fm-<GROUP_NAME>'] {

  .fm-item.fm-field {
    position: unset;
  }
}
```

Here I have the FM field wrapper highlighted, which I hope demonstrates the issue.

![Screen Shot 2023-04-24 at 4 38 24 PM](https://user-images.githubusercontent.com/2059404/234138445-cecc31ca-17c5-4884-b6c4-39fb449a4071.png)
